Add overview panel
Kitware/UPennContrast pull request #507
Opened 2023-08-31 15:51 UTC by bruyeret

Close #450

2023-08-31 16:16 UTC, arjunrajlab approved these changes
Tested and it looks great to me!

2023-08-31 16:22 UTC, arjunrajlab commented
Actually, I'm seeing a slight problem with this file:

https://www.dropbox.com/scl/fi/ola4b1iphhgenl98zxkca/20230807_133502_470_LVE016-HKC-1dpi-HSV-1-WT-ICP4_GFP-MX1_Cy3-IFNb_A594-IRF3_Cy5-DDX58_Cy7_Stitched.nd2?rlkey=2unlgixyv2pn6x7zi3odgcqgy&dl=0

If you load that file, the overview doesn't quite match the image. The overview cuts off the bottom and right.

2023-08-31 16:23 UTC, arjunrajlab requested changes
Actually, I'm seeing a slight problem with this file:

https://www.dropbox.com/scl/fi/ola4b1iphhgenl98zxkca/20230807_133502_470_LVE016-HKC-1dpi-HSV-1-WT-ICP4_GFP-MX1_Cy3-IFNb_A594-IRF3_Cy5-DDX58_Cy7_Stitched.nd2?rlkey=2unlgixyv2pn6x7zi3odgcqgy&dl=0

If you load that file, the overview doesn't quite match the image. The overview cuts off the bottom and right.

2023-09-01 14:43 UTC, arjunrajlab approved these changes
Just tested and it is working great, thanks! Fine to merge for me.

2023-09-01 14:44 UTC, bruyeret commented
It should be fixed now @arjunrajlab 
Thank you @manthey !

![image](https://github.com/Kitware/UPennContrast/assets/90781029/9c4ce518-2b7b-4e2d-a46a-ba6aab291d62)

2023-09-11 08:03 UTC, luciemac commented on src/components/ImageOverview.vue
> +    [true, true],
Can you add some comments?

2023-09-11 08:26 UTC, luciemac commented
then, LGTM

2023-09-11 11:28 UTC, bruyeret commented
I added a comment and made the code clearer, do you see another place where the code would need comments?

2023-09-11 11:47 UTC, luciemac commented
nope looks great now ! Thanks

2023-09-11 11:47 UTC, merged