Add image scale settings
Kitware/UPennContrast pull request #522
Opened 2023-09-11 12:34 UTC by bruyeret

Add a new panel in the collection view
Make scalebar clickable, open a dialog to tweak scales

I added most of the features of issue 498:
- In the collection view, the user can set the values for the different scales
- In the image viewer, the user can open a dialog by clicking on the scalebar to have more options. In this dialog, the scale is saved in the dataset view and the user has the option to save the scale in collection and to reset to dataset default. It behaves like the contrasts.
- The scalebar uses the pixel size given in the dataset view or in the configuration.
- Workers have access to scales: `params["scales"]["pixelSize"]` contains both `value` and `unit`

Close #498

2023-09-11 13:43 UTC, arjunrajlab requested changes
Looks good! Only thing is the color of the scale bar would be better as white rather than black because it is often very hard to see:

<img width="377" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/38a20c07-ab3f-4ec3-bb9a-36c53f79173a">

2023-09-11 15:03 UTC, bruyeret commented
It should be fixed now, do you approve @arjunrajlab ?
![image](https://github.com/Kitware/UPennContrast/assets/90781029/498e1a3c-3adf-4c7e-b430-faa63d4a192b)

2023-09-11 15:08 UTC, arjunrajlab commented
Is it possible to make the line a little bit thicker looking?

2023-09-11 15:38 UTC, bruyeret commented
Yes of course, it has size 2px, and now it has size 4px, do you want something thicker?
![image](https://github.com/Kitware/UPennContrast/assets/90781029/d7460ad0-6aab-434a-aa78-6079054a47b1)

2023-09-11 15:42 UTC, arjunrajlab commented
Let's go for 5pt, that should be fine! Also, we don't need the little tick marks on the two ends, just the bar in the middle is fine. But also no problem if it's hard to change, minor point.

2023-09-11 15:50 UTC, bruyeret commented
Does it look good?

![image](https://github.com/Kitware/UPennContrast/assets/90781029/5c85b95e-6a6d-459d-b168-279aaea32583)

2023-09-11 15:52 UTC, arjunrajlab commented
Beautiful, perfect!

2023-09-12 07:53 UTC, luciemac commented on src/store/model.ts
> +export function exampleConfigurationBase(): IDatasetConfigurationBase {
Why don't you keep it as a `const` ?

2023-09-12 08:06 UTC, bruyeret commented on src/store/model.ts
> +export function exampleConfigurationBase(): IDatasetConfigurationBase {
It is to avoid aliasing

2023-09-12 11:49 UTC, merged